### ISSUE TITLE
small data set for first trials

### ISSUE THREAD

**Issue by SteffenMeinecke** [balmorelcommunity/Balmorel#16]
Dear Balmorel community,
I like to check out the basic functionality and adaptability of Balmorel for future investigations. For that I have the free license of GAMS installed on my windows machine which should be sufficient for basic trials. Unfortunately, I did not find any small example data sets. The data provided at https://github.com/balmorelcommunity/Balmorel_data lead to the GAMS error `The model exceeds the demo license limits for linear models of more than 2000 rows or columns`.
Maybe you can help me making the first step with Balmorel via providing a simple example data set?

**Comment by Mathias157** [comment]
Dear Steffen,

I know this is probably irrelevant to you now, but I have created a tiny scenario that should be possible to run in a new "balmorel-demo" branch. I think this is a good thing to have in general.. :)

The branch README is hopefully self-explanatory, but I will repeat it here:
- You still need to use the data from the master branch in Balmorel_data and put it in base/data (not balmorel_demo/data as it will overwrite the data files that make the scenario "tiny" !)
- You will need to run the Balmorel.gms file in balmorel_demo/model
