### ISSUE TITLE
Access to generic model

### ISSUE THREAD

**Issue by gorkemgungormetu** [balmorelcommunity/Balmorel#21]
Hello,

Is the [Balmorel ](https://balmorel.com/) website obsolete?

Thanks,

Görkem Güngör

**Comment by Mathias157** [comment]
Hi,

Yes it is unfortunately not in development at the time.
In the DTU team, we have updated the openmod wiki if this is of any help:
https://wiki.openmod-initiative.org/wiki/Balmorel
